// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drhqhjfbcatnifqrnyrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyaHFoamZiY2F0bmlmcXJueXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTU5OTEsImV4cCI6MjA3MDM5MTk5MX0.obbkk6NaAdnALv96JGpnZiOOX7LYudOe4rJLY0q8dCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});