name: Scheduled Vercel Deploy
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
